# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lucie Montoya et François Marceau
tagline:             On va se marier !
url:                 http://marceau.ink/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lucie Montoya et François Marceau
  url:               https://marceau.ink/
  email:             contact@marceau.ink

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
